# Generated by Django 5.1.2 on 2024-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField(auto_now_add=True)),
                ('zip_num', models.IntegerField()),
                ('copyright_link', models.CharField(max_length=100)),
                ('whatsapp_link', models.CharField(max_length=100)),
                ('twitter_link', models.CharField(max_length=100)),
                ('facebook_link', models.CharField(max_length=100)),
                ('linkedin_link', models.CharField(max_length=100)),
                ('github_link', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('a_logo', models.ImageField(upload_to='logo')),
                ('cv', models.FileField(upload_to='Cv')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'db_table': 'About',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo')),
                ('carousel1', models.ImageField(upload_to='carousel')),
                ('carousel2', models.ImageField(upload_to='carousel')),
            ],
            options={
                'verbose_name': 'CompanyProfile',
                'verbose_name_plural': 'CompanyProfile',
                'db_table': 'CompanyProfile',
                'managed': True,
            },
        ),
    ]
