# Generated by Django 5.1.2 on 2024-10-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0004_alter_about_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_me',
            field=models.TextField(default='about me at the top'),
        ),
    ]
