# Generated by Django 5.1.2 on 2024-10-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0005_about_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='date_of_birth',
            field=models.DurationField(default='duration'),
        ),
    ]
