# Generated by Django 5.1.2 on 2024-10-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0007_alter_about_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
