# Generated by Django 5.1.2 on 2024-10-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0008_alter_about_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='t_dob',
            field=models.DateField(default=12),
            preserve_default=False,
        ),
    ]
