# Generated by Django 5.1.2 on 2024-10-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0010_alter_about_t_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='t_dob',
            field=models.DateField(default='twelve'),
        ),
    ]
