# Generated by Django 5.1.2 on 2024-10-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0011_alter_about_t_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='t_dob',
        ),
    ]
