# Generated by Django 5.1.2 on 2024-10-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0012_remove_about_t_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='datte',
            field=models.DateField(default=True),
        ),
    ]
