# Generated by Django 5.1.2 on 2024-10-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0013_about_datte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='datte',
            field=models.DateField(auto_now_add=True),
        ),
    ]
