# Generated by Django 5.1.2 on 2024-10-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0014_alter_about_datte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='datte',
        ),
    ]
