# Generated by Django 5.1.2 on 2024-10-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0016_alter_about_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='dob',
            new_name='date_created',
        ),
    ]
