# Generated by Django 5.1.2 on 2024-10-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0017_rename_dob_about_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DurationField()),
                ('duration', models.CharField(max_length=300)),
                ('degree', models.CharField(max_length=300)),
                ('school', models.CharField(max_length=300)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'db_table': 'Certification',
                'managed': True,
            },
        ),
    ]
