# Generated by Django 5.1.2 on 2024-10-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0018_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='address',
            field=models.CharField(default='my school or institute address', max_length=300),
            preserve_default=False,
        ),
    ]
