# Generated by Django 5.1.2 on 2024-10-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0019_certification_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='date_started',
        ),
    ]
