# Generated by Django 5.1.2 on 2024-10-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0020_remove_certification_date_ended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='year',
        ),
    ]
